version: "3.7"

services:
  app:
    expose:
      - 9000
    volumes:
      - ./.env:/config/.env
      - .:/app
      - ./ci-cd/build-configs/www.conf:/usr/local/etc/php-fpm.d/www.conf
    build:
      context: .
      dockerfile: ./ci-cd/build-configs/Dockerfile
    depends_on:
      - mysql
  web:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./ci-cd/build-configs/vhost1.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  mysql:
    image: mysql:8.0
    volumes:
        - db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: cookies
        MYSQL_PASSWORD: pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  db_data: