name: "Deploy project"
on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Run Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            cd CookiesShop;
            git pull origin master;
            echo "fetch updates...";
            cd ..;
            cp -r CookiesShop/* public_html;
            echo "apply updates...";
            cd public_html;
            composer install;
            echo "run migrations";
            php artisan migrate;
            npm i;
            npm run build;
            cp -r public/storage/images/* storage/images/;
            echo "Done!";